package org.nbgames.numberguesser;

import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
@ConvertAsProperties(
        dtd = "-//org.nbgames.numberguesser//NumberGuesser//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "NumberGuesserTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@Messages({
    "CTL_GameVersion=1.0.0",
    "CTL_GameCopyright=© 2013 Patrik Karlsson"})
public final class GameTopComponent extends org.nbgames.core.game.GameTopComponent {

    private GameController mGameController;

    public GameTopComponent() {
        initComponents();
        setName(Bundle.CTL_GameTitle());

        mGameController = new GameController(this, Bundle.CTL_GameTitle(), Bundle.CTL_GameVersion(), Bundle.CTL_GameCopyright(), null);
    }

    @Override
    public JPanel getTopPanel() {
        return mTopPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTopPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        mTopPanel.setBackground(new java.awt.Color(153, 153, 0));
        mTopPanel.setLayout(new java.awt.BorderLayout());
        add(mTopPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mTopPanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        mGameController.startNewGame();
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
}
