package org.nbgames.numberguesser;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.NbPreferences;

final class OptionPanel extends javax.swing.JPanel implements DocumentListener {

    private final OptionPanelController mController;

    OptionPanel(OptionPanelController controller) {
        mController = controller;
        initComponents();

        minFormattedTextField.getDocument().addDocumentListener(this);
        maxFormattedTextField.getDocument().addDocumentListener(this);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        mController.changed();
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        mController.changed();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        mController.changed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromLabel = new javax.swing.JLabel();
        minFormattedTextField = new javax.swing.JFormattedTextField();
        toLabel = new javax.swing.JLabel();
        maxFormattedTextField = new javax.swing.JFormattedTextField();

        org.openide.awt.Mnemonics.setLocalizedText(fromLabel, org.openide.util.NbBundle.getMessage(OptionPanel.class, "OptionPanel.fromLabel.text")); // NOI18N

        minFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        minFormattedTextField.setText(org.openide.util.NbBundle.getMessage(OptionPanel.class, "OptionPanel.minFormattedTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(toLabel, org.openide.util.NbBundle.getMessage(OptionPanel.class, "OptionPanel.toLabel.text")); // NOI18N

        maxFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        maxFormattedTextField.setText(org.openide.util.NbBundle.getMessage(OptionPanel.class, "OptionPanel.maxFormattedTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromLabel)
                    .addComponent(minFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(toLabel)
                    .addComponent(maxFormattedTextField))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        minFormattedTextField.setValue(NbPreferences.forModule(OptionPanel.class).getLong(Prefs.KEY_MIN, Prefs.KEY_MIN_DEF));
        maxFormattedTextField.setValue(NbPreferences.forModule(OptionPanel.class).getLong(Prefs.KEY_MAX, Prefs.KEY_MAX_DEF));
    }

    void store() {
        NbPreferences.forModule(OptionPanel.class).putLong(Prefs.KEY_MIN, (Long) minFormattedTextField.getValue());
        NbPreferences.forModule(OptionPanel.class).putLong(Prefs.KEY_MAX, (Long) maxFormattedTextField.getValue());
    }

    boolean valid() {
        long min;
        long max;

        min = (Long) minFormattedTextField.getValue();
        max = (Long) maxFormattedTextField.getValue();

        return max > min;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fromLabel;
    private javax.swing.JFormattedTextField maxFormattedTextField;
    private javax.swing.JFormattedTextField minFormattedTextField;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
