/*
 * Copyright 2016 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.nbgames.core.ui;

/**
 *
 * @author Patrik Karlsson
 */
public class HelpPanel extends javax.swing.JPanel {

    private StringBuilder mCssBuilder;

    /**
     * Creates new form OptionsPanel
     */
    public HelpPanel() {
        initComponents();
        init();
    }

    private void init() {
        mCssBuilder = new StringBuilder("<html>");
        mCssBuilder.append("<head><style>");
        mCssBuilder.append("h1 { font-size: xx-large; margin-bottom: 0px; text-align: center;}");
        mCssBuilder.append("h2 { font-size: xx-large; margin-bottom: 0px; }");
        mCssBuilder.append("h3 { font-size: x-large; margin-bottom: 0px; }");
        mCssBuilder.append("body {margin-left: 16px;margin-right: 16px; font-size: medium; }");
        mCssBuilder.append("p {font-size: large; margin-bottom: 4px;margin-top: 4px;}");
        mCssBuilder.append("ul { margin-left: 16px; }");
        mCssBuilder.append("li { font-size: large; }");
        mCssBuilder.append("</style></head>");
    }

    public void load(String string) {
        textPane.setText(mCssBuilder.toString() + string);
        textPane.setCaretPosition(0);
        scrollPane.getVerticalScrollBar().setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane.setBorder(null);

        textPane.setEditable(false);
        textPane.setContentType("text/html"); // NOI18N
        textPane.setFocusable(false);
        scrollPane.setViewportView(textPane);

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables

}
