package org.nbgames.yaya;

import javax.swing.JPanel;
import org.nbgames.core.game.GameTopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.nbgames.yaya//Yaya//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "YayaTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@Messages({
    "CTL_GameVersion=1.0.0",
    "CTL_GameCopyright=© 2013 Patrik Karlsson"})

public final class YayaTopComponent extends GameTopComponent {

    private final YayaController mGameController;

    public YayaTopComponent() {
        initComponents();
        String name = NbBundle.getMessage(YayaTopComponent.class, "CTL_Name");
        setName(name);
        mGameController = new YayaController(this, name, Bundle.CTL_GameVersion(), Bundle.CTL_GameCopyright(), "Dice/Yaya");
    }

    @Override
    public JPanel getTopPanel() {
        return mTopPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTopPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        mTopPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout mTopPanelLayout = new javax.swing.GroupLayout(mTopPanel);
        mTopPanel.setLayout(mTopPanelLayout);
        mTopPanelLayout.setHorizontalGroup(
            mTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mTopPanelLayout.setVerticalGroup(
            mTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(mTopPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mTopPanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
