package org.nbgames.yaya;

import org.nbgames.core.game.GameTopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.nbgames.yaya//Yaya//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "YayaTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@Messages({
    "CTL_InfoVersion=0.0.1",
    "CTL_InfoDescription=Yet Another Yahtzee",
    "CTL_InfoCopyright=© 2013 Patrik Karlsson"})

public final class YayaTopComponent extends GameTopComponent {

    private final YayaController mGameController;

    public YayaTopComponent() {
        initComponents();
        String name = NbBundle.getMessage(YayaTopComponent.class, "CTL_Name");
        setName(name);
        mGameController = new YayaController(this, name, Bundle.CTL_InfoVersion(), Bundle.CTL_InfoDescription(), Bundle.CTL_InfoCopyright(), "Dice/Yaya");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        mGameController.requestNewGame();
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    @Override
    protected void componentDeactivated() {
        super.componentDeactivated();
        setActionCategoryVisible("Yaya", false);
    }

    @Override
    protected void componentActivated() {
        super.componentActivated();
        setActionCategoryVisible("Yaya", true);
    }

}
