package org.nbgames.yaya;

import java.awt.BorderLayout;
import java.awt.Dimension;
import org.nbgames.core.NbGames;
import org.nbgames.core.dice.DiceBoard;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class YayaPanel extends org.nbgames.core.game.GamePanel {

    private YayaController mGameController;

    /**
     * Creates new form GamePanel
     */
    public YayaPanel() {
        initComponents();

        Dimension dimension = new Dimension(400, 300);

        setMinimumSize(dimension);
        setPreferredSize(dimension);
        setSize(dimension);
//        setOpaque(false);
        setLayout(new BorderLayout());

        DiceBoard board = new DiceBoard(5);
        add(board.getPanel(), BorderLayout.SOUTH);
        board.newTurn();

    }

    public YayaPanel(YayaController gameController) {
        this();

        mGameController = gameController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void startNewGame() {
        NbGames.log("Yaya: startNewGame");
    }
}
