package org.nbgames.yaya;

import org.nbgames.core.game.NewGamePanel;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class YayaNewGamePanel extends NewGamePanel {

    /**
     * Creates new form YayaNewGamePanel
     */
    public YayaNewGamePanel() {
        initComponents();
        numOfPlayersComboBox.setSelectedIndex(Options.INSTANCE.getNumOfPlayers() - 1);
    }

    @Override
    protected void save() {
        Options.INSTANCE.setNumOfPlayers(numOfPlayersComboBox.getSelectedIndex() + 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        variantLabel = new javax.swing.JLabel();
        variantComboBox = new javax.swing.JComboBox();
        numOfPlayersLabel = new javax.swing.JLabel();
        numOfPlayersComboBox = new javax.swing.JComboBox();

        typeLabel.setLabelFor(typeComboBox);
        org.openide.awt.Mnemonics.setLocalizedText(typeLabel, org.openide.util.NbBundle.getMessage(YayaNewGamePanel.class, "YayaNewGamePanel.typeLabel.text")); // NOI18N

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yahtzee" }));

        variantLabel.setLabelFor(variantComboBox);
        org.openide.awt.Mnemonics.setLocalizedText(variantLabel, org.openide.util.NbBundle.getMessage(YayaNewGamePanel.class, "YayaNewGamePanel.variantLabel.text")); // NOI18N

        variantComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard" }));
        variantComboBox.setEnabled(false);

        numOfPlayersLabel.setLabelFor(numOfPlayersComboBox);
        org.openide.awt.Mnemonics.setLocalizedText(numOfPlayersLabel, org.openide.util.NbBundle.getMessage(YayaNewGamePanel.class, "YayaNewGamePanel.numOfPlayersLabel.text")); // NOI18N

        numOfPlayersComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(variantLabel)
                            .addComponent(numOfPlayersLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(typeComboBox, 0, 204, Short.MAX_VALUE)
                    .addComponent(variantComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numOfPlayersComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typeLabel)
                .addGap(4, 4, 4)
                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numOfPlayersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numOfPlayersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox numOfPlayersComboBox;
    private javax.swing.JLabel numOfPlayersLabel;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox variantComboBox;
    private javax.swing.JLabel variantLabel;
    // End of variables declaration//GEN-END:variables
}
