package org.nbgames.gunu;

import java.util.prefs.PreferenceChangeEvent;
import java.util.prefs.PreferenceChangeListener;
import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
@ConvertAsProperties(
        dtd = "-//org.nbgames.numberguesser//NumberGuesser//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "NumberGuesserTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@Messages({
    "CTL_GameVersion=1.0.0",
    "CTL_GameCopyright=© 2013 Patrik Karlsson"})
public final class GameTopComponent extends org.nbgames.core.game.GameTopComponent {

    private final GameController mGameController;

    public GameTopComponent() {
        initComponents();
        String name = NbBundle.getMessage(GameTopComponent.class, "CTL_Name");
        setName(name);
        mTopPanel.setBackground(Options.INSTANCE.getColorBackground());
        Options.INSTANCE.getPreferences().addPreferenceChangeListener(new PreferenceChangeListener() {

            @Override
            public void preferenceChange(PreferenceChangeEvent evt) {
                if (evt.getKey().equals(Options.KEY_COLOR_BACKGROUND)) {
                    mTopPanel.setBackground(Options.INSTANCE.getColorBackground());
                }
            }
        });
        mGameController = new GameController(this, name, Bundle.CTL_GameVersion(), Bundle.CTL_GameCopyright(), "Logic/NumberGuesser");
    }

    @Override
    public JPanel getTopPanel() {
        return mTopPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTopPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        mTopPanel.setBackground(new java.awt.Color(153, 153, 0));
        mTopPanel.setLayout(new java.awt.BorderLayout());
        add(mTopPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mTopPanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        mGameController.startNewGame();
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
}
