package org.nbgames.gunu;

import javax.swing.DefaultComboBoxModel;
import org.nbgames.core.Player;
import org.nbgames.core.PlayerManager;
import org.nbgames.core.game.NewGamePanel;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class GunuNewGamePanel extends NewGamePanel {

    /**
     * Creates new form GunuNewGamePanel
     */
    public GunuNewGamePanel() {
        initComponents();
        Object[] players = PlayerManager.INSTANCE.getPlayersArray();
        playerComboBox.setModel(new DefaultComboBoxModel(players));
    }

    @Override
    protected void saveState() {
        String name = ((Player) playerComboBox.getSelectedItem()).getName();
        Options.INSTANCE.setPlayer(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLabel = new javax.swing.JLabel();
        playerComboBox = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(messageLabel, org.openide.util.NbBundle.getMessage(GunuNewGamePanel.class, "GunuNewGamePanel.messageLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel)
                    .addComponent(playerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addGap(18, 18, 18)
                .addComponent(playerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    private javax.swing.JComboBox playerComboBox;
    // End of variables declaration//GEN-END:variables
}
