package org.nbgames.gunu;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import se.trixon.almond.dialogs.AColorChooser;
import se.trixon.almond.swing.ColorChooserButton;

final class OptionPanel extends javax.swing.JPanel implements DocumentListener {

    private final OptionPanelController mController;
    private final ColorChooserButton colorButton;
    private final Options mOptions = Options.INSTANCE;

    OptionPanel(OptionPanelController controller) {
        mController = controller;
        initComponents();

        colorButton = (ColorChooserButton) backgroundButton;
        minFormattedTextField.getDocument().addDocumentListener(this);
        maxFormattedTextField.getDocument().addDocumentListener(this);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        mController.changed();
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        mController.changed();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        mController.changed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromLabel = new javax.swing.JLabel();
        minFormattedTextField = new javax.swing.JFormattedTextField();
        toLabel = new javax.swing.JLabel();
        maxFormattedTextField = new javax.swing.JFormattedTextField();
        backgroundButton = new se.trixon.almond.swing.ColorChooserButton();

        org.openide.awt.Mnemonics.setLocalizedText(fromLabel, org.openide.util.NbBundle.getMessage(OptionPanel.class, "OptionPanel.fromLabel.text")); // NOI18N

        minFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        minFormattedTextField.setText("-1000"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(toLabel, org.openide.util.NbBundle.getMessage(OptionPanel.class, "OptionPanel.toLabel.text")); // NOI18N

        maxFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        maxFormattedTextField.setText("1000"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(backgroundButton, org.openide.util.NbBundle.getMessage(OptionPanel.class, "OptionPanel.backgroundButton.text")); // NOI18N
        backgroundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromLabel)
                    .addComponent(toLabel)
                    .addComponent(backgroundButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(maxFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(minFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backgroundButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundButtonActionPerformed
        colorButton.setColor(AColorChooser.showDialog(colorButton.getColor()));
    }//GEN-LAST:event_backgroundButtonActionPerformed

    void load() {
        minFormattedTextField.setValue(mOptions.getMin());
        maxFormattedTextField.setValue(mOptions.getMax());
        colorButton.setColor(mOptions.getColorBackground());
    }

    void store() {
        mOptions.setMin((Long) minFormattedTextField.getValue());
        mOptions.setMax((Long) maxFormattedTextField.getValue());
        mOptions.setColorBackground(colorButton.getColor());
    }

    boolean valid() {
        long min;
        long max;

        min = (Long) minFormattedTextField.getValue();
        max = (Long) maxFormattedTextField.getValue();

        return max > min;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backgroundButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JFormattedTextField maxFormattedTextField;
    private javax.swing.JFormattedTextField minFormattedTextField;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
